language: node_js
node_js:
- node
script:
- 
deploy:
  provider: firebase
  token:
    secure: "kS93BIYib1sgUfTht8lZ+EajLPeEhSei800lBA9eBEn994piNPTbBlb8hmnmcQ/LkNe2mfG58qCOIOUux21x9FMpuoHEdKi7eOSpkWjtIoZqBFLjjKNg5PkuBt0oV4wVMbiVZHKGXG5dO32zHrOfSURtv7Lk5t+vB1uHlxbG+tnPDiTRonoTjKfkXeTdTEx7MPZyXz37HQ1VMdhP+K/2Qk5YajV6X2dpWXU64ZydSHR2ictNvQ6J8DhW75946Kuc8SEhN7G8yuVfcf6d2sIMiW2GxC8gCGvcxPdSEXy4zK6u3BmMuQZHdQACvIAVxZJX3QSr9wxEmifFGhoHd2zDTLViZ7eoaeHiESZG4LiIk4g4FIX/0z9DXOPgAgdKLswi4E0qN4ojo0lizJsmnBsZQvDf53i8PUuBrEBGmujnj0LDaI5XBq+24LVqMb0WImPbqRSacSgGjD7y9SG2IcrxA2ZgBv7/FKZ+si2bou9uHFrSdtx+CtW1WCWWqjqk/T761Q+7Lb9wRS3AwWLGlsllmmajfgxSRqZ2hmhc7/FLBnkr0VjxMRprh0UgGaCM9bu8gww1Agx06RAPu2b4djtqdqzPZXfbfLHVQ1haCqJvuXYnizF17CSGO9CjdpBuxK4mRJV8mTQ5s82itizY2NBLwZ0wgQkIfMzHE8NYC6nlZZo="
before_script:
  - "npm i -g gatsby"
  - "npm i"
after_script:
  - "npm run deploy"